# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CubicGalileonEmu',
                'doc_host': 'https://nesar.github.io',
                'git_url': 'https://github.com/nesar/CubicGalileonEmu',
                'lib_path': 'CubicGalileonEmu'},
  'syms': {'CubicGalileonEmu.core': {'CubicGalileonEmu.core.foo': ('core.html#foo', 'CubicGalileonEmu/core.py')}}}
