# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_emu.ipynb.

# %% auto 0
__all__ = ['Emu']

# %% ../nbs/03_emu.ipynb 3
from sepia.SepiaModel import SepiaModel
from sepia.SepiaData import SepiaData
from sepia.SepiaPredict import SepiaEmulatorPrediction
from sepia.SepiaPredict import SepiaFullPrediction
from sepia.SepiaPredict import SepiaXvalEmulatorPrediction
from sepia.SepiaSharedThetaModels import SepiaSharedThetaModels
from PIL import Image
import sepia.SepiaPlot as SepiaPlot

# %% ../nbs/03_emu.ipynb 4
def Emu(model, 
        model_params, 
        ip):
    
    if len(ip.shape) == 1:
        sensDes = np.expand_dims(ip, axis=0)
        
    else:
        sensDes = ip
        
    pred = SepiaEmulatorPrediction(t_pred=sensDes, samples=model_params, model=model)
    sens_pred_samps = pred.get_y()
    sens_pred = np.mean(sens_pred_samps, axis=0).transpose()
    return sens_pred
