# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_gp.ipynb.

# %% auto 0
__all__ = ['MODEL_DIR', 'MODEL_FILE', 'MODEL_DIR_PATH', 'do_gp_train', 'gp_load', 'gp_load_all']

# %% ../nbs/02_gp.ipynb 3
from sepia.SepiaModel import SepiaModel
from sepia.SepiaData import SepiaData
import pkg_resources
import os

# %% ../nbs/02_gp.ipynb 4
MODEL_DIR = "model/"
MODEL_FILE = pkg_resources.resource_stream("CubicGalileonEmu", MODEL_DIR + "README.txt").name
MODEL_DIR_PATH = os.path.dirname(MODEL_FILE)

# %% ../nbs/02_gp.ipynb 5
def do_gp_train(sepia_model:SepiaModel=None, # Input data in SEPIA format, after PCA
                model_file:str=None, #pickle file path
               ) -> SepiaModel: # sepia.SepiaModel.SepiaModel after GP
    
    ## Also check: https://github.com/lanl/SEPIA/blob/master/examples/Synthetic_toy_examples/multivariate_example_with_prediction.ipynb
    
    sepia_model.tune_step_sizes(50, 20, update_vals=True)
    sepia_model.do_mcmc(1000)
    sepia_model.save_model_info(model_file)
    return sepia_model

# %% ../nbs/02_gp.ipynb 7
def gp_load(sepia_model:SepiaModel=None, # Input data in SEPIA format (Pre-PCA is fine? -- CHECK)
            model_file:str=MODEL_DIR_PATH + 'multivariate_model', #pickle file path
    ) -> SepiaModel: # sepia.SepiaModel.SepiaModel
    
    # make sure this model was instantiated with the same input data as the model corresonding to this saved model info.

    # if os.path.isfile(model_file+'.pkl'):
    try:
        sepia_model.restore_model_info(model_file)
        return sepia_model
        
    except FileNotFoundError as e:
        print(e.errno)    

# %% ../nbs/02_gp.ipynb 8
def gp_load_all():
    pass
