# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_mcmc.ipynb.

# %% auto 0
__all__ = ['ln_prior', 'ln_like', 'ln_prob', 'burn_in', 'mcmc_run']

# %% ../nbs/04_mcmc.ipynb 3
def ln_prior(): pass

def ln_like(): pass

def ln_prob(): pass

def burn_in(): pass

def mcmc_run(): pass
