name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SEPIA
      run: |
        git clone https://github.com/lanl/SEPIA.git
        cd SEPIA
        pip install -e .[sepia]  # Install SEPIA package

    - name: Use quarto-ghp action
      uses: fastai/workflows/quarto-ghp@master
